import yaml from "yaml";

// ============================================================================
// Types
// ============================================================================

export type RenderType =
  | "text"
  | "number"
  | "currency"
  | "date"
  | "badge"
  | "link"
  | "address";

export type CurrencyType = "DOT" | "USD" | "USDC" | "USDT";

export type BadgeVariant =
  | "default"
  | "secondary"
  | "destructive"
  | "outline"
  | "success"
  | "warning";

export interface ColumnRenderConfig {
  displayName?: string;
  render: RenderType;
  // Currency options
  currency?: CurrencyType;
  decimals?: number;
  // Date options
  format?: "date" | "datetime";
  // Badge options
  variants?: Record<string, BadgeVariant>;
  // Link options
  urlTemplate?: string;
  urlField?: string; // Field in row that contains the URL
  // Address options
  truncate?: boolean;
  // Number options
  color?: "green" | "red";
}

interface ColumnConfig {
  columns: Record<string, ColumnRenderConfig>;
  tables: Record<string, Record<string, ColumnRenderConfig>>;
}

// ============================================================================
// State
// ============================================================================

let config: ColumnConfig = { columns: {}, tables: {} };
let loaded = false;

// ============================================================================
// Config Loading
// ============================================================================

export async function loadColumnConfig(): Promise<void> {
  if (loaded) return;
  try {
    const response = await fetch("/config/column-config.yaml");
    if (response.ok) {
      const text = await response.text();
      config = yaml.parse(text) || { columns: {}, tables: {} };
    }
  } catch (e) {
    console.warn("Failed to load column config:", e);
  }
  loaded = true;
}

// ============================================================================
// Config Lookup
// ============================================================================

const defaultConfig: ColumnRenderConfig = { render: "text" };

export function getColumnConfig(
  tableName: string,
  columnName: string
): ColumnRenderConfig {
  // 1. Check table-specific override
  const tableConfig = config.tables?.[tableName]?.[columnName];
  if (tableConfig) {
    return { ...defaultConfig, ...tableConfig };
  }

  // 2. Check global column config
  const globalConfig = config.columns?.[columnName];
  if (globalConfig) {
    return { ...defaultConfig, ...globalConfig };
  }

  // 3. Auto-detect from column name patterns
  return autoDetectConfig(columnName);
}

function autoDetectConfig(columnName: string): ColumnRenderConfig {
  const name = columnName.toLowerCase();

  // Currency patterns
  if (columnName.startsWith("DOT_")) {
    return { render: "currency", currency: "DOT", decimals: 0 };
  }
  if (columnName.startsWith("USD_")) {
    return { render: "currency", currency: "USD", decimals: 0 };
  }
  if (columnName.startsWith("USDC_")) {
    return { render: "currency", currency: "USDC", decimals: 2 };
  }
  if (columnName.startsWith("USDT_")) {
    return { render: "currency", currency: "USDT", decimals: 2 };
  }

  // Date patterns
  if (name.includes("_time") || name.includes("_date") || name === "createdat") {
    return { render: "date", format: "date" };
  }

  // Status pattern
  if (name === "status" || name.endsWith("_status")) {
    return {
      render: "badge",
      variants: {
        Executed: "success",
        Approved: "success",
        Paid: "success",
        Rejected: "destructive",
        Cancelled: "destructive",
        Expired: "destructive",
        default: "outline",
      },
    };
  }

  // Address patterns
  if (
    name === "beneficiary" ||
    name === "address" ||
    name === "who" ||
    name.endsWith("_address")
  ) {
    return { render: "address", truncate: true };
  }

  // Default to text
  return { render: "text" };
}

// ============================================================================
// Display Name
// ============================================================================

export function getColumnDisplayName(
  tableName: string,
  columnName: string
): string {
  const cfg = getColumnConfig(tableName, columnName);
  if (cfg.displayName) return cfg.displayName;

  // Auto-generate from column name
  return autoGenerateDisplayName(columnName);
}

function autoGenerateDisplayName(columnName: string): string {
  return columnName
    .replace(/_/g, " ")
    .replace(/\./g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase())
    .replace(/\bDot\b/gi, "DOT")
    .replace(/\bUsd\b/gi, "USD")
    .replace(/\bUsdc\b/gi, "USDC")
    .replace(/\bUsdt\b/gi, "USDT");
}

// ============================================================================
// Value Formatting (for text output)
// ============================================================================

export function formatValue(
  value: unknown,
  config: ColumnRenderConfig
): string {
  if (value === null || value === undefined) return "-";

  switch (config.render) {
    case "currency":
      return formatCurrencyValue(value as number, config);
    case "number":
      return formatNumberValue(value as number, config);
    case "date":
      return formatDateValue(value as string, config);
    case "address":
      return formatAddressValue(value as string, config);
    default:
      return String(value);
  }
}

function formatCurrencyValue(
  value: number,
  config: ColumnRenderConfig
): string {
  if (value === null || value === undefined) return "-";

  const decimals = config.decimals ?? 0;
  const formatted = new Intl.NumberFormat("en-US", {
    minimumFractionDigits: decimals,
    maximumFractionDigits: decimals,
  }).format(value);

  const currency = config.currency || "DOT";
  return `${formatted} ${currency}`;
}

function formatNumberValue(value: number, config: ColumnRenderConfig): string {
  if (value === null || value === undefined) return "-";

  const decimals = config.decimals ?? 2;
  return new Intl.NumberFormat("en-US", {
    minimumFractionDigits: 0,
    maximumFractionDigits: decimals,
  }).format(value);
}

function formatDateValue(value: string, config: ColumnRenderConfig): string {
  if (!value) return "-";

  const date = new Date(value);
  if (config.format === "datetime") {
    return date.toLocaleString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  }
  return date.toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

function formatAddressValue(value: string, config: ColumnRenderConfig): string {
  if (!value) return "-";
  if (config.truncate && value.length > 16) {
    return `${value.slice(0, 8)}...${value.slice(-6)}`;
  }
  return value;
}

// ============================================================================
// Abbreviated Formatting (for chart axes)
// ============================================================================

export function formatAbbreviated(
  value: number,
  config: ColumnRenderConfig
): string {
  if (value === null || value === undefined) return "-";

  const absValue = Math.abs(value);
  let formatted: string;
  let suffix = "";

  if (absValue >= 1_000_000_000) {
    formatted = (value / 1_000_000_000).toPrecision(3);
    suffix = "B";
  } else if (absValue >= 1_000_000) {
    formatted = (value / 1_000_000).toPrecision(3);
    suffix = "M";
  } else if (absValue >= 1_000) {
    formatted = (value / 1_000).toPrecision(3);
    suffix = "K";
  } else {
    formatted = value.toPrecision(3);
  }

  // Remove trailing zeros after decimal
  formatted = parseFloat(formatted).toString();

  const currency = config.currency;
  if (currency) {
    return `${formatted}${suffix} ${currency}`;
  }
  return `${formatted}${suffix}`;
}

// ============================================================================
// Badge Variant Lookup
// ============================================================================

export function getBadgeVariant(
  value: string,
  config: ColumnRenderConfig
): BadgeVariant {
  if (!config.variants) return "outline";

  const variant = config.variants[value];
  if (variant) return variant;

  return config.variants["default"] || "outline";
}

// ============================================================================
// Link URL Generation
// ============================================================================

export function getLinkUrl(
  value: unknown,
  config: ColumnRenderConfig,
  row?: Record<string, unknown>
): string | null {
  // If urlField is specified, get URL from the row data
  if (config.urlField && row) {
    const url = row[config.urlField];
    return url ? String(url) : null;
  }

  // If urlTemplate is specified, interpolate the value
  if (config.urlTemplate) {
    return config.urlTemplate.replace("{value}", String(value));
  }

  return null;
}

// ============================================================================
// Re-export for backwards compatibility
// ============================================================================

// These functions maintain backwards compatibility with code that imported from column-display-names.ts
export { loadColumnConfig as loadColumnNameOverrides };
